// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBi4gh4ycQj_8H8WC1dH_-smxDmmcVgc',
    appId: '1:691680597057:web:6b9b4829da425e261ea2c0',
    messagingSenderId: '691680597057',
    projectId: 'flashwords-75197',
    authDomain: 'flashwords-75197.firebaseapp.com',
    storageBucket: 'flashwords-75197.appspot.com',
    measurementId: 'G-9JG0Q4SEB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiD_H3-Nt78Z50nhBPyT0zpZ8iCQNWklw',
    appId: '1:691680597057:android:15a7de6cae978ff71ea2c0',
    messagingSenderId: '691680597057',
    projectId: 'flashwords-75197',
    storageBucket: 'flashwords-75197.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAU2blrDnn9njzMwEygL5bEnwASZXlY4I',
    appId: '1:691680597057:ios:55b24c78f6d3b8f81ea2c0',
    messagingSenderId: '691680597057',
    projectId: 'flashwords-75197',
    storageBucket: 'flashwords-75197.appspot.com',
    iosClientId: '691680597057-hoduehngpai19u00aq5n1rsdtmu535ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashwords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAU2blrDnn9njzMwEygL5bEnwASZXlY4I',
    appId: '1:691680597057:ios:55b24c78f6d3b8f81ea2c0',
    messagingSenderId: '691680597057',
    projectId: 'flashwords-75197',
    storageBucket: 'flashwords-75197.appspot.com',
    iosClientId: '691680597057-hoduehngpai19u00aq5n1rsdtmu535ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashwords',
  );
}
